import type { Metadata } from 'next'
import { ClerkProvider} from '@clerk/nextjs'
import './globals.css'

import { Sora, Inter } from "next/font/google";



const sora = Sora({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-sora",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  

  return (

    <html lang="en">
            <body className={`${sora.variable} ${inter.variable} bg-[#0B0B0D]`}>

        
   <ClerkProvider>

          {children}
               </ClerkProvider>
      </body>
    </html>
  

  );
}
